### PR TITLE
metfrag tool (v2.4.5+galaxy3) AND metfrag_vis tool (v2.4.5+galaxy0)

### PR DESCRIPTION
**Pull request by Tomnl**
* Metfrag visualisation tool added (initial submission for toolshed)
 * For standard metfrag tool the following updates
    * Option added to include all fragment peaks in output
    * Additional meta columns added for output (if available) e.g. retention time
    * Py3 vs Py2 fixes
    * Adduct can be added either selected via the tool or via the MSP file

@korseby - see[ test output ](https://github.com/computational-metabolomics/metfrag-galaxy/blob/v2.4.5%2Bgalaxy3/tools/metfrag/test-data/winter_pos.tabular) - would this be suitable for the viz tool?

### CODE REVIEW

**Comment by korseby** [comment]
Hi @Tomnl ,

Thanks for looking into the matter. I will have time on Monday to have a detailed look and to test it out. I found some things that are unclear to me:
- could you add the column `precursorRT`? `retention_time` refers to the rt used in the library?
- could you add a column with the `precursorMz`? These should be the same values as found in the MSP and metfrag-cli command line.
- The column `PeakListString` looks a bit odd. The first value is the mz? the second value (after the `_` is the intensity value? Is this the direct string used in the command line of metfrag-cli? I'm asking because the intensity does not seem to have decimal places... It should look more like this `53.2165603637695_219.481;53.3158149719238_284.551; ...` But it could be my fault as I recognize the sample names. ;) So, I'm just asking here...

I'll send you a msp file in a private email with a msp-file which I am currently working with (and also used for testing the viz script). Can you try that one and send me the output privately? (Data is not yet published but will be hopefully soon.)

Otherwise the matrix looks fine.

**Comment by Tomnl** [comment]
Thanks for that @korseby. Sorry to answer your questions with more questions...

- Do you need the column to be specifically named `precursorRT` for retention time?
  - The `retention_time` column in the output will be the retention time determined by the following regexes for a [generic MSP file](https://github.com/computational-metabolomics/metfrag-galaxy/blob/v2.4.5+galaxy3/tools/metfrag/metfrag.py#L97-L99) and the following regex for [MassBank format](https://github.com/computational-metabolomics/metfrag-galaxy/blob/v2.4.5+galaxy3/tools/metfrag/metfrag.py#L113-L114)
  - I can change the column name in the output if that is required
- Do you need the column to be specifically named `precursorMZ` for the precursor mz?
  - The `precursor_mz` column is determined by the following regexes for a [generic MSP file](https://github.com/computational-metabolomics/metfrag-galaxy/blob/v2.4.5+galaxy3/tools/metfrag/metfrag.py#L91-L92) and the following regexes for [MassBank](https://github.com/computational-metabolomics/metfrag-galaxy/blob/v2.4.5+galaxy3/tools/metfrag/metfrag.py#L109-L110)
  - I can change the column name in the output if that is required
- I use `PeakListPath` for the fragmentation data using MetFrag CLI not `PeakListString`. The PeakListString i provided is created using this [MSP file](https://github.com/computational-metabolomics/metfrag-galaxy/blob/v2.4.5%2Bgalaxy3/tools/metfrag/test-data/winter_pos.msp). So for the first spectra in that msp file would be `121.099329887276_182;149.133267159026_510;150.14016979533_114` in the format `mz_intensity;mz_intensity;mz_intensity.....etc`

I hope that clears up a few things. 

I will run on the example you sent via email and send back the results via email

**Comment by korseby** [comment]
Indeed, in the original phenomenal-version of metfrag-vis we had `parentRT` and `parentMZ` columns (Sorry, they were not called `precursor`-something... mixed that up).

See here: https://github.com/korseby/container-msnbase/blob/f889d81bc8fcd3d75f9e7fec6ffc0d5279fe2de2/scripts/metfrag-vis2.r#L194 

So it would be good to have them here too.

**Comment by Tomnl** [comment]
Hi @korseby 

I have updated the vis tool so that it should pass all the planemo linting and tests. Note this mean't the id had to change from "metfrag-vis" to "metfrag_vis" as the hyphen is not allowed in the id of the tool.

I have also updated the python code so that it is PEP8 formatted - which is a check performed for most of the tools that get added to "usegalaxy" - unfortunately that meant updating the line limit to 79... but at least both the python scripts used in the repo are using the same style.

Anyway - I have also added some updates to the standard metfrag tool - most importantly an option to choose the adducts used at the tool level rather than just at the MSP level.

If you have time - please could you check that the MetFrag Vis tool  still works with your setup?

FYI  @RJMW

**Comment by korseby** [comment]
Sure I will test. Will do it early next week.

**Comment by korseby** [comment]
In my local Galaxy the `metfrag-vis` module currently fails to run. The reason is whitespace formatting which at some point is wrong in your version... Not sure exactly where, though. 

When I add a `print(row)` on line 391 of the `metfrag-vis.py` the output is for some reason not a normal `dict` but an `OrderedDict`.  At first I though it might be a wrong delimiter, but that does not seem to be the case. As a result of `row` not being a normal dictionary, the script cannot find `MetFragCLIString` and fails with an error.

Here is how it looks like with your script:
```python
OrderedDict([('AlignmentID,MetFragCLIString,name,num_peaks,precursor_mz,precursor_type,retention_time,sample_name,CompoundName,ExplPeaks,FormulasOfExplPeaks,FragmenterScore,FragmenterScore_Values,IUPACName,Identifier,InChI,InChIKey,InChIKey1,InChIKey2,InChIKey3,MaximumTreeDepth,MolecularFormula,MonoisotopicMass,NoExplPeaks,NumberPeaksUsed,OfflineMetFusionScore,SMILES,Score,XlogP3', '1,"metfrag SampleName=2_metfrag_result MetFragScoreTypes=FragmenterScore,OfflineMetFusionScore NeutralPrecursorMass=133.892236363645 FragmentPeakMatchRelativeMassDeviation=5.0 DatabaseSearchRelativeMassDeviation=10.0 MetFragDatabaseType=PubChem PrecursorIonMode=-1 PeakListPath=./temp/2_tmpspec.txt IsPositiveIonMode=False MetFragScoreWeights=1.0,1.0 ResultsPath=./temp/ NumberThreads=1 FragmentPeakMatchAbsoluteMassDeviation=0.001 MetFragCandidateWriter=CSV PeakListString=57.0331085358366_3414.94;59.0123711881343_8243.66;69.0329772680022_3729.58;70.0283217709276_1619.79;71.0122599247865_32347.3;73.0155569538774_8253.01;75.0071982753934_9884.1;85.02795429433_2371.08;87.0435574913145_21740.3;89.0228272281266_8188.66;90.0288663350096_4897.13;91.0271384585252_2205.48;100.932075500488_1617.36;103.98795027429_2690.65;104.984687528577_7536.09;107.034838529717_2022.42;114.01814927788_3429.26;115.007073874308_51271.7;115.919285413059_3549.24;131.888570505749_7003.8;132.866457780198_292645;132.901043204911_187710;133.037150030485_40805;133.885589571231_4796.87;134.045863639847_15413.8",neg446,25,132.884960363645,[M-H]-,13.6288698,2_metfrag_result,,NA,NA,0.0,NA,dichlorophosphinothious acid,71358619,InChI=1S/Cl2HPS/c1-3(2)4/h4H,NRONNKOYXWZKFM-UHFFFAOYSA-N,NRONNKOYXWZKFM,UHFFFAOYSA,,2,Cl2HPS,133.891364,0,19,0.1898049983533291,P(S)(Cl)Cl,0.9975394399168811,2.0')])
```

Here's the output of how it should look like:
```python
{'AlignmentID': '1', 'MetFragCLIString': 'metfrag SampleName=2_metfrag_result MetFragScoreTypes=FragmenterScore,OfflineMetFusionScore NeutralPrecursorMass=133.892236363645 FragmentPeakMatchRelativeMassDeviation=5.0 DatabaseSearchRelativeMassDeviation=10.0 MetFragDatabaseType=PubChem PrecursorIonMode=-1 PeakListPath=./temp/2_tmpspec.txt IsPositiveIonMode=False MetFragScoreWeights=1.0,1.0 ResultsPath=./temp/ NumberThreads=1 FragmentPeakMatchAbsoluteMassDeviation=0.001 MetFragCandidateWriter=CSV PeakListString=57.0331085358366_3414.94;59.0123711881343_8243.66;69.0329772680022_3729.58;70.0283217709276_1619.79;71.0122599247865_32347.3;73.0155569538774_8253.01;75.0071982753934_9884.1;85.02795429433_2371.08;87.0435574913145_21740.3;89.0228272281266_8188.66;90.0288663350096_4897.13;91.0271384585252_2205.48;100.932075500488_1617.36;103.98795027429_2690.65;104.984687528577_7536.09;107.034838529717_2022.42;114.01814927788_3429.26;115.007073874308_51271.7;115.919285413059_3549.24;131.888570505749_7003.8;132.866457780198_292645;132.901043204911_187710;133.037150030485_40805;133.885589571231_4796.87;134.045863639847_15413.8', 'name': 'neg446', 'num_peaks': '25', 'precursor_mz': '132.884960363645', 'precursor_type': '[M-H]-', 'retention_time': '13.6288698', 'sample_name': '2_metfrag_result', 'CompoundName': '', 'ExplPeaks': 'NA', 'FormulasOfExplPeaks': 'NA', 'FragmenterScore': '0.0', 'FragmenterScore_Values': 'NA', 'IUPACName': 'dichlorophosphinothious acid', 'Identifier': '71358619', 'InChI': 'InChI=1S/Cl2HPS/c1-3(2)4/h4H', 'InChIKey': 'NRONNKOYXWZKFM-UHFFFAOYSA-N', 'InChIKey1': 'NRONNKOYXWZKFM', 'InChIKey2': 'UHFFFAOYSA', 'InChIKey3': '', 'MaximumTreeDepth': '2', 'MolecularFormula': 'Cl2HPS', 'MonoisotopicMass': '133.891364', 'NoExplPeaks': '0', 'NumberPeaksUsed': '19', 'OfflineMetFusionScore': '0.1898049983533291', 'SMILES': 'P(S)(Cl)Cl', 'Score': '0.9975394399168811', 'XlogP3': '2.0'}
```

I also tested on my Mac. When I remove the blank lines without code and adapt whitespaces to tabs instead of 4 spaces and not limited to 80 characters, the script runs again...

**Comment by Tomnl** [comment]
Hi @korseby 

Sorry for the delay in replying to this.

I think there was a problem automatically getting the file separator. Should be fixed now (it runs fine on both my Ubuntu and mac setups)

**Comment by korseby** [comment]
Hi @Tomnl ,

your latest changes fix the problems I have seen. I tested the script with a small dataset and it works.

PR can be merged. :)

Best wishes, *Kristian

**Comment by Tomnl** [comment]
Thanks @korseby!

Looks like the deploy was successful as well - so the metfrag vis tool is now available on the Galaxy toolshed along with the latest metfrag Galaxy tool
 
https://toolshed.g2.bx.psu.edu/view/computational-metabolomics/metfrag_vis/3dbe79671820

**Comment by korseby** [comment]
Thanks @Tomnl for merging the tool so fast into the galaxy toolshed. I have requested that it is installed on metabolomics.usegalaxy.eu . We will have a few people who will do some tests. Likely in a few weeks I'll do another PR regarding some suggested imrovements to the tool by the testers.

**Pull request merged**
