### PR TITLE
Feature: metfrag-vis module

### PR DESCRIPTION
**Pull request by korseby**
Hi @Tomnl ,

here is the PR regarding the metfrag-vis module.

There are some new dependencies which need to be resolved. Do you install metfrag-galaxy via conda? Chris from our group has just added a new dependency `cd-inchi-to-svg` so that we only need to add the required python modules `pubchempy`, `matplotlib`, `numpy` . How do we do that in the best way? Should I do a PR to the bioconda for their metfrag?

Anyway. Please test and let me know.

Best wishes, *Kristian

### CODE REVIEW

**Comment by Tomnl** [comment]
Thanks @korseby  - this is great.

The only dependency the metfrag-galaxy tool currenty requires is `metfrag` from bioconda ( as the tool it just uses the base python to run the script).

If you need to add additional packages for the vis tool. You should add them them as additional requirements [section](https://github.com/korseby/metfrag-galaxy/blob/master/tools/metfrag/metfrag-vis.xml#L9).  `pubchempy`, `matplotlib` and `numpy` are already available in bioconda/conda so are easy to add. 

Where is `cd-inchi-to-svg` used? is it a python package on pypi? This will need to be added to  bioconda by adding a pull request

Bioconda is really for biological focused

**Comment by korseby** [comment]
I added the dependencies. A few days ago we added the cd-inchi-to-svg to bioconda, so all dependencies should be readily available.

I also noticed that somehow Python 2.7 is referenced. I have written the tool in Python 3.8, I guess it will also work with earlier versions but likely not with Python 2.7. How do we change that?

**Comment by Tomnl** [comment]
Great. Thanks @korseby.

Regarding python3 - I think you would just put python and the version you need into the requirements.

I will update my script for the metfrag tool so that it is py3 compatible as well

**Comment by korseby** [comment]
Ok. I added python 3.7.3 as dependency. I think, just play on the safe side and not add too latest versions of python.

Let me know when you need more from me.

**Comment by Tomnl** [comment]
Thanks @korseby 

I am going to merge this into branch for the next release and try to get the test passing with planemo

**Review by Tomnl — APPROVED** [review]

**Pull request merged**
