### PR TITLE
[WIP] Add parameters and threshold for metfrag

### PR DESCRIPTION
**Pull request by jsaintvanne**
Hi,

Here are some additions for metfrag. I added some parameters that metfrag can take in its command line and also two thresholds that we can have after metfrag process.

It can allow users to select some parameters and generate less than millions of results !

Be free to say if that is a good idea to have this or not and if some things can be add.

Thanks

### CODE REVIEW

**Comment by Tomnl** [comment]
Hi @jsaintvanne,

I am running this pull request locally but I am getting an error

JobOutputsError: History item  different than expected, difference (using diff):
( /home/tomnl/Dropbox/code/metfrag_julien/tools/metfrag/test-data/metfrag.tabular v. /tmp/tmpuy1aRjmetfrag.tabular )
--- local_file
+++ history_data
@@ -1,16 +1 @@

I think with the default settings using the example MSP file with give no results rows in the output.

Did the unit-tests pass locally when you tested?

I think the travis failing though is an unrelated error

**Comment by jsaintvanne** [comment]
Ho I have just answer it on the issue !

The only one problem I have locally is only this empty file because of the format of msp file...
Maybe I can change the msp input ?

**Comment by Tomnl** [comment]
OK, in  the future we need to update so that it can handle both "standard" MSP and the massbank format.

For now, just update the MSP format to fit with the script and make sure the test works locally and push.

**Comment by RJMW** [comment]
This issue / request is somewhat related - msp files with space separated columns.

https://github.com/computational-metabolomics/cfm-galaxy/issues/4

**Comment by Tomnl** [comment]
I think the travis failing is unrelated though (at least for the failures observed at the moment).

Just requires updating the yaml file to the following 
https://github.com/computational-metabolomics/metfrag-galaxy/blob/phen_msp_to_metrag_update/.travis.yml

Previously it was hard coded to an older version of planemo and galaxy

**Comment by jsaintvanne** [comment]
Yes I'm updating the input.msp with actual create_msp output (not the one where you choose massbank or standard but the previous one). And I will push it !

**Comment by jsaintvanne** [comment]
Made a new PR on the new branch with old 2 PR ! I close this one

**Pull request closed without merging**
